apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-pod
  name: test-pod
spec:
  nodeSelector:
    node-role.kubernetes.io/master: ''
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
  containers:
  - image: docker.io/mossicrue/kup:v4.5-new
    name: test-pod
    resources: {}
    command: ["ls", "/mnt/node"]
    volumeMounts:
    - name: node-mount
      mountPath: /mnt/node
    securityContext:
      privileged: true
      runAsUser: 0
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: node-mount
    hostPath:
      path: /
      type: ''